### ISSUE TITLE
部署在本地的没有登录验证，是要在py文件里修改啥吗

### ISSUE THREAD

**Issue by muyudegit** [MorvanZhou/rethink#2]
部署在本地的没有登录验证，是要在py文件里修改啥吗

**Comment by MorvanZhou** [comment]
这个还没添加，我规划到下一个版本中

在 2024年4月5日，08:48，muyudegit ***@***.***> 写道：

﻿

部署在本地的没有登录验证，是要在py文件里修改啥吗

**Comment by MorvanZhou** [comment]
在 rethink.run(password="xxx") 中添加了私有化版本的密码鉴权
 
https://github.com/MorvanZhou/rethink/commit/71483154bdd7800ce27a476c59faf40e812ef57b
