### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Jackiexiao** [MorvanZhou/rethink#4]
1. 请问后续会出 本地 exe 版本吗
2. 项目似乎使用 vue 写的前端？但源码中只有 app.js，似乎是 vue 编译后的内容，如果是的话，这一部分代码后续会开源吗
3. 自动推荐笔记是个好主意，不过实现一个 obsidian 插件似乎会更好？

**Comment by MorvanZhou** [comment]
1. 由于是 python 后端，全套逻辑做成 exe 的可能性比较小。但未来有考虑将前端构建成安装包，采用云服务的形态。不过这个还不太确定。
2. 是 vue 写的。我没有开放前端项目，目前已在 py 中加入 plugin 能力，可以第三方贡献插件，我会在这里写如何写插件 (文档正在写) https://rethink.run/home/zh/plugins/
3. 是一个不错的途径。不过还是想自己尝试一下
